### ISSUE TITLE
windows  10.  - unable to build

### ISSUE THREAD

**Issue by RenatasDidysis** [kvark128/OnlineLibrary#1]
1. Unable to build
OS : windows 10.

build.sh  
then "go run ."

go run .

and after that errors 

# github.com/kvark128/OnlineLibrary/internal/minimp3
internal\minimp3\minimp3.go:4:10: fatal error: minimp3.h: No such file or directory
    4 | //#include <minimp3.h>
      |          ^~~~~~~~~~~
compilation terminated.
# github.com/kvark128/OnlineLibrary/internal/sonic
internal\sonic\sonic.go:4:10: fatal error: sonic.h: No such file or directory
    4 | //#include <sonic.h>
      |          ^~~~~~~~~
compilation terminated.

2. also need program print screens
3. compiled app also needed

**Comment by kvark128** [comment]
Running the build.sh script creates the final executable OnlineLibrary.exe. To build, in addition to go, you also need gcc. Do you have any errors while executing this script?

**Comment by RenatasDidysis** [comment]
not working:

1. downloaded zip file from github
2. extracted
3. run build.sh 
Z:\downloads\OnlineLibrary-master\OnlineLibrary-master> build.sh

gcc.exe: error: Z:/downloads/OnlineLibrary-master/OnlineLibrary-master/external/sonic/sonic.c: No such file or directory
gcc.exe: fatal error: no input files
compilation terminated.
C:\TDM-GCC-64\bin\ar.exe: Z:/downloads/OnlineLibrary-master/OnlineLibrary-master/external/sonic/sonic.o: No such file or directory
install: cannot stat '/z/downloads/OnlineLibrary-master/OnlineLibrary-master/external/sonic/sonic.h': No such file or directory
install: cannot stat '/z/downloads/OnlineLibrary-master/OnlineLibrary-master/external/minimp3/minimp3.h': No such file or directory
rm: cannot remove '/z/downloads/OnlineLibrary-master/OnlineLibrary-master/external/sonic/*.o': No such file or directory
# github.com/kvark128/OnlineLibrary/internal/minimp3
internal\minimp3\minimp3.go:4:10: fatal error: minimp3.h: No such file or directory
    4 | //#include <minimp3.h>
      |          ^~~~~~~~~~~
compilation terminated.
# github.com/kvark128/OnlineLibrary/internal/sonic
internal\sonic\sonic.go:4:10: fatal error: sonic.h: No such file or directory
    4 | //#include <sonic.h>
      |          ^~~~~~~~~
compilation terminated.

**Comment by kvark128** [comment]
Extracting from a zip file will not work. You must clone the git repository with all submodules:
git clone --recursive https://github.com/kvark128/OnlineLibrary.git
The --recursive option is required to download submodules such as sonic and minimp3.
