### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by BraunTas** [kvark128/OnlineLibrary#3]
an error occurs during compilation
mingw32-make: *** No rule to make target 'sonic.c', needed by '.build/amd64/sonic.o'.  Stop.

**Comment by kvark128** [comment]
You need to clone the repository with all submodules:
`git clone --recurse-submodules https://github.com/kvark128/OnlineLibrary.git`

**Comment by BraunTas** [comment]
mkdir -p .build/amd64
Ошибка в синтаксисе команды.
Makefile:40: recipe for target '.build/amd64/sonic.o' failed
mingw32-make: *** [.build/amd64/sonic.o] Error 1
this is the error

**Comment by kvark128** [comment]
On Windows I recommend building from the msys2 environment:
https://www.msys2.org/

**Comment by BraunTas** [comment]
specify the commands for compilation

**Comment by BraunTas** [comment]
please give compilation instructions

**Comment by kvark128** [comment]
1. Install msys2 as described under the Installation heading on the main project page and run the ucrt64 environment.
2. In the ucrt64 terminal, install the necessary dependencies:
`pacman -S mingw-w64-ucrt-x86_64-toolchain mingw-w64-ucrt-x86_64-go git make`
3. Clone the repository with all submodules:
`git clone --recurse-submodules https://github.com/kvark128/OnlineLibrary.git`
4. Go to the OnlineLibrary directory and run the make command. If the build occurs without errors, the executable file OnlineLibrary.exe will appear in the same directory.

**Comment by BraunTas** [comment]
mkdir -p .build/amd64
x86_64-w64-mingw32-gcc -Wall -Wextra -Werror -Wno-unused-function -Wno-unused-parameter -Wno-sign-compare -O2 -c -o .build/amd64/sonic.o external/sonic/sonic.c
mkdir -p .build/amd64/lib
ar rcs .build/amd64/lib/libsonic.a .build/amd64/sonic.o
install -D -p external/sonic/sonic.h .build/amd64/include/sonic.h
install -D -p external/minimp3/minimp3.h .build/amd64/include/minimp3.h
go run cmd/rsrc/rsrc.go -arch amd64 -manifest OnlineLibrary.exe.manifest -o rsrc_windows_amd64.syso
go: cannot find GOROOT directory: 'go' binary is trimmed and GOROOT is not set
make: *** [Makefile:33: rsrc_windows_amd64.syso] Error 2

**Comment by BraunTas** [comment]
When you move the exe file to another folder, the Russian language disappears

**Comment by BraunTas** [comment]
thank you very much for your help it worked

**Comment by BraunTas** [comment]
Why don't you have any releases?
