### ISSUE TITLE
Program error

### ISSUE THREAD

**Issue by BraunTas** [kvark128/OnlineLibrary#4]
Hello, I have a very strange error when logging into my account, it says that there is no Internet, although it is

**Comment by BraunTas** [comment]
![Снимок](https://user-images.githubusercontent.com/85228877/176031237-6ca72efd-2b49-43c0-972c-b5928b894d66.PNG)

**Comment by BraunTas** [comment]
> I meant what library service do you use? Remote server may not work stably.

and what to eat
do.av3715.ru

**Comment by kvark128** [comment]
Can you provide session.log file from the program's working directory?

**Comment by BraunTas** [comment]
> Can you provide session.log file from the program's working directory?

I beg your pardon, I didn’t indicate the fool before do.av3715.ru https

**Comment by kvark128** [comment]
OK, can the issue be closed?
